apply plugin: "org.jlleitschuh.gradle.ktlint"

ktlint {
    version = "1.1.1"
    android = true
    verbose = true
    outputColorName = "RED"


    /**
     * To view ktlint reports switch your IDE to Project mode then go to:
     * app -> reports -> ktlint
     */
    reporters {
        reporter "plain"
        reporter "checkstyle"
        reporter "html"
    }
    filter {
        exclude("**/generated/**")
        include("**/kotlin/**")

        /**
         * Exclude the file with the experimental context parameter temporarily.
         * Watch-out for latest release based on below raised issue:
         * (https://github.com/JLLeitschuh/ktlint-gradle/issues/912)
         */
        exclude("**/manager/ContextParameter.kt")
    }
}
