name: Android Build Deployment

on:
  push:
    branches:
      - develop
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Set up Encoded Keystore File
        run: |
          mkdir -p $GITHUB_WORKSPACE/release/secret
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > $GITHUB_WORKSPACE/release/secret/android-keystore.jks

      - name: Set up local.properties
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/local.properties
          ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}
          EOF

      - name: Set up google-services.json files
        run: |
          mkdir -p app/src/dev app/src/live

          # Write google-services.json files for DEV & LIVE
          echo "${{ secrets.GOOGLE_SERVICES_JSON_DEV }}" | base64 --decode > app/src/dev/google-services.json
          echo "${{ secrets.GOOGLE_SERVICES_JSON_LIVE }}" | base64 --decode > app/src/live/google-services.json

      - name: Deploy Android Build
        env:
          POKEDEX_FIREBASE_APP_ID: ${{ secrets.POKEDEX_FIREBASE_APP_ID }}
          POKEDEX_FIREBASE_CREDENTIAL_CONTENT: ${{ secrets.POKEDEX_FIREBASE_CREDENTIAL_CONTENT }}
          SLACK_DEPLOYMENT_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_WEBHOOK_URL }}
        run: |
          if [ "$GITHUB_REF" = "refs/heads/develop" ]; then
            bundle exec fastlane deploy_dev
          elif [ "$GITHUB_REF" = "refs/heads/master" ]; then
            bundle exec fastlane deploy_live
          fi

      - name: Cleanup secrets
        if: always()
        run: |
          rm -rf \
            local.properties \
            app/src/dev/google-services.json \
            app/src/live/google-services.json \
            $GITHUB_WORKSPACE/release/secret/android-keystore.jks
